# a simple DAO for a database that does CRUD operations on a cycling routes table
#author: Gerry Callaghan

import mysql.connector
import urllib.parse # this might be needed to parse the strava URL 
#from testing_dbconfig import config_details
from dbconfig_pythonanywhere import config_details


class RouteDAO:

    host = config_details['host']
    user = config_details['user']
    password = config_details['password']
    database = config_details['database']
    connection = ""
    cursor = ""


    def get_cursor(self):
        self.connection = mysql.connector.connect(
            host=self.host,
            user=self.user,
            password=self.password,
            database=self.database
        )
        self.cursor = self.connection.cursor()
        return self.cursor

    def close_all(self):
        self.cursor.close()
        self.connection.close()


    # creating data in a database
    def create_route(self, route):
        mycursor = self.get_cursor()# this creates a connection to the database and return a cursor object that we can use to execute SQL commands
        sql = "Insert into routes_table (destination, route_map, distance, elevation) values (%s, %s,%s, %s)"
        values = (route.get("destination"), route.get("route_map"), route.get("distance"),route.get("elevation")) # .get(" ") pulls the title, author, and price FROM the dictionary object which is the format it is stored in the database. If not set, get will return None
       
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function, which will insert the new record into the database. 
        # The %s in the sql string are placeholders for the values that will be passed in the values tuple. This is a common way to prevent SQL injection attacks, 
        # because it ensures that the values are properly escaped before being inserted into the database.

        self.connection.commit() # this is necessary to save the changes to the database, if commit is not called, the changes will not be saved and will be lost when the connection is closed.
        #print("1 record inserted, ID:", mycursor.lastrowid) # this is just for testing, it will print the id of the record that was just inserted so you know it was inserted correctly. 
        # The lastrowid property of the cursor object will return the id of the last record that was inserted into the database, 
        # this is useful for confirming that the insert operation was successful and for retrieving the id of the new record if needed.
        
        route["id"] = mycursor.lastrowid # we can NOW add the id to the route dictionary object that was passed in, so that when we return the route, it will have the NEW id that was just autogenerated by the database
        self.close_all() # this will close the connection to the database, to free up resources and prevent potential issues with too many open connections simultaneously.
        return route


    # reading data from a database
    def get_all_routes(self):
        mycursor = self.get_cursor()
        sql = "Select * from routes_table Order by destination, id" # this will select all records from the routes_table and order them by id in ascending order, so that the records are returned in the order they were inserted into the database.
        
        mycursor.execute(sql) 
        results = mycursor.fetchall() # this will return all records from the database as a list of tuples, where each tuple represents a record. If no records are found, it will return an empty list.
        #print(results) # this is just for testing, it will print the record that was found, so you can confirm that all the records were retrieved from the database.

        route_list = []
        for result in results:
            route_list.append(self.convert_to_dict(result)) # this will convert each tuple in the results list to a dictionary object using the convert_to_dict() function 
    
        self.close_all()
        return route_list


    # finding one route by id
    def find_route_by_id(self, id):
        mycursor = self.get_cursor()
        try:
            sql = "Select * from routes_table where id = %s"
            values = (id,)
            mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function, which will insert the new record into the database. 
            results = mycursor.fetchone() # this will return a single record from the database that matches the specified id, as a tuple. 
            # If no record is found, it will return None. If multiple records are found (which shouldn't happen if id is a primary key), 
            # it will return the first record that matches the criteria.
            #print(results) # this is just for testing, it will print the record that was found, so you can confirm that the correct record was retrieved from the database.
            if results:
                print(results)
            else:
                print(f"Route with ID: {id} not found")
        except Exception as e:
            print("Error finding route by id:", e)
            return None
        except mysql.connector.errors.InternalError as e:
            print(f"Database error: {e}")
            return None
        except mysql.connector.errors.IntegrityError as e:
            print(f"\nID: {id} is not valid, it must be an integer, error: {e}")
            return None
        except Exception as e:
            print(f"Unexpected error: {e}")
            return None

        route_found = self.convert_to_dict(results) # this will convert the tuple returned by fetchone() to a dictionary object using the convert_to_dict() function, 
        # so that it can be easily returned in the JSON response.

        self.close_all()
        return route_found


    # updating data in a database
    def update_route(self, id, route):
        route_to_be_updated= self.find_route_by_id(id)
        mycursor = self.get_cursor()
        sql = "Update routes_table set destination = %s, route_map = %s, distance = %s, elevation = %s where id = %s"
        values = (route.get("destination"), route.get("route_map"), route.get("distance"),route.get("elevation"),id) # use .get(" ")to get the title, author, and price out of the dictionary object. If not set, get will return None
        
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function
        self.connection.commit() # this is necessary to save the update to the database, if you don't call commit, the changes will not be saved and will be lost when the connection is closed.
        #updated_id = mycursor.lastrowid#
        #print("1 record updated, ID:", routeid, "new route details are:", route.get("destination"), route.get("route_map"), route.get("distance"), route.get("elevation")) # this is for testing and prints the id of the record that was updated 
        # so you know you updated the correct record 

        self.close_all()
        return route, route_to_be_updated # we return the route that was just updated, so that we can see what was updated in the test output, 
        # and also return the original route before it was updated, so that we can see the difference in the test output

    # deleting data from a database
    def delete_route(self, id):
        route_to_be_deleted= self.find_route_by_id(id)
        mycursor = self.get_cursor()
        sql = "Delete from routes_table where id = %s"
        values = (id,)
        
        mycursor.execute(sql, values) # this passes the sql string and the values tuple to the execute function
        self.connection.commit() # this is necessary to save the deletion to the database, 
        #print("1 record deleted") # this is for testing and print a message to confirm that the record was deleted, so you know the delete operation was successful.

        self.close_all()
        return route_to_be_deleted # we can return the route that was just deleted, so that we can see what was deleted

    def convert_to_dict(self, resultline):  # this will convert each tuple in the results list to a dictionary object , 
            # This function will take in a tuple that represents a record from the database, and convert it to a dictionary object 
            # with the keys being the "column" names and the values being the corresponding values for each column for that record. 
             # This is useful because it allows us to easily return the data in a JSON response, which is a common format for APIs. 
        routekeys = ["id", "destination", "route_map", "distance", "elevation"]
        current_key = 0
        route = {} # set up an empty dictionary object to hold the key value pairs for the route record
        for attrib in resultline: # for each attribute in the tuple that represents the record, we will add a key value pair to the route dictionary object, 
            # where the key is the corresponding column name from the routekeys list, and the value is the attribute from the tuple.
            route[routekeys[current_key]] = attrib # this will add a key value pair to the route dictionary object, 
            # where the key is the corresponding column name from the list, and the value is the attribute for that column from the tuple.
            # First time through the loop, current_key will be 0, so the key will be "id" and the value will be the first attribute in the tuple (which is the id of the route).
            # second time through the loop, current_key will be 1, so the key will be "destination" and the value will be the second attribute in the tuple (which is the destination of the route), and so on for route_map, distance, and elevation.    
            current_key += 1
        return route
        

routeDAO = RouteDAO() # make an instance of the DAO class to use again
